{
    "data": {
        "tasks": {
            "forum": {
                "saveMessage": null,
                "__typename": "ForumMutations"
            },
            "__typename": "TaskMutations"
        }
    },
    "errors": [
        {
            "message": "null value in column \"heading\" of relation \"tasks_forummessage\" violates not-null constraint\nDETAIL:  Failing row contains (f, null, 2024-05-13 16:52:56.42829+00, 2024-05-13 16:52:56.428568+00, 0, 0, 1, cdaa42ae-e0f3-4c32-97df-cdaea780dcdf, <p>test&amp;</p>, null, f, f, 6b8601cc-e4fc-4f07-a911-fdeb1a38319d, 8add5308-8db9-40fd-8891-a3e26ac74463, 0af8eca0-12aa-40e7-a5ac-e2f64f9f9883).\n",
            "locations": [
                {
                    "line": 4,
                    "column": 7
                }
            ],
            "path": [
                "tasks",
                "forum",
                "saveMessage"
            ],
            "extensions": {
                "exception": {
                    "stacktrace": [
                        "Traceback (most recent call last):",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py\", line 89, in _execute",
                        "    return self.cursor.execute(sql, params)",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "psycopg2.errors.NotNullViolation: null value in column \"heading\" of relation \"tasks_forummessage\" violates not-null constraint",
                        "DETAIL:  Failing row contains (f, null, 2024-05-13 16:52:56.42829+00, 2024-05-13 16:52:56.428568+00, 0, 0, 1, cdaa42ae-e0f3-4c32-97df-cdaea780dcdf, <p>test&amp;</p>, null, f, f, 6b8601cc-e4fc-4f07-a911-fdeb1a38319d, 8add5308-8db9-40fd-8891-a3e26ac74463, 0af8eca0-12aa-40e7-a5ac-e2f64f9f9883).",
                        "",
                        "The above exception was the direct cause of the following exception:",
                        "Traceback (most recent call last):",
                        "  File \"/usr/local/lib/python3.11/site-packages/graphql/execution/execute.py\", line 521, in execute_field",
                        "    result = resolve_fn(source, info, **args)",
                        "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/application/src/uc-logging/uc_logging/middleware/transfer_current_user.py\", line 27, in transfer_current_user",
                        "    return resolver(obj, info, **kwargs)",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/application/src/uc-logging/uc_logging/middleware/store_client_ip.py\", line 14, in store_client_ip",
                        "    return resolver(obj, info, **kwargs)",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/application/src/uc-ariadne/uc_ariadne/middleware/slow_resolver.py\", line 6, in slow_resolver",
                        "    value = resolver(obj, info, **args)",
                        "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/application/src/uc-ariadne/uc_ariadne/decorators/current_user.py\", line 37, in wrapper",
                        "    return func(*args, **kwargs, **get_current_user_from_info(args, kwargs))",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/application/tasks/graphql_ariadne/app/mutations.py\", line 63, in resolve_save_forum_message",
                        "    return ForumService().save_message(",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/application/tasks/services/forum_service/forum_service.py\", line 286, in save_message",
                        "    message = ForumMessage.objects.create(",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/models/manager.py\", line 87, in manager_method",
                        "    return getattr(self.get_queryset(), name)(*args, **kwargs)",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 658, in create",
                        "    obj.save(force_insert=True, using=self.db)",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/models/base.py\", line 814, in save",
                        "    self.save_base(",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/models/base.py\", line 877, in save_base",
                        "    updated = self._save_table(",
                        "              ^^^^^^^^^^^^^^^^^",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/models/base.py\", line 1020, in _save_table",
                        "    results = self._do_insert(",
                        "              ^^^^^^^^^^^^^^^^",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/models/base.py\", line 1061, in _do_insert",
                        "    return manager._insert(",
                        "           ^^^^^^^^^^^^^^^^",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/models/manager.py\", line 87, in manager_method",
                        "    return getattr(self.get_queryset(), name)(*args, **kwargs)",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 1805, in _insert",
                        "    return query.get_compiler(using=using).execute_sql(returning_fields)",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py\", line 1822, in execute_sql",
                        "    cursor.execute(sql, params)",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py\", line 102, in execute",
                        "    return super().execute(sql, params)",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py\", line 67, in execute",
                        "    return self._execute_with_wrappers(",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py\", line 80, in _execute_with_wrappers",
                        "    return executor(sql, params, many, context)",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py\", line 84, in _execute",
                        "    with self.db.wrap_database_errors:",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/utils.py\", line 91, in __exit__",
                        "    raise dj_exc_value.with_traceback(traceback) from exc_value",
                        "  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py\", line 89, in _execute",
                        "    return self.cursor.execute(sql, params)",
                        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
                        "django.db.utils.IntegrityError: null value in column \"heading\" of relation \"tasks_forummessage\" violates not-null constraint",
                        "DETAIL:  Failing row contains (f, null, 2024-05-13 16:52:56.42829+00, 2024-05-13 16:52:56.428568+00, 0, 0, 1, cdaa42ae-e0f3-4c32-97df-cdaea780dcdf, <p>test&amp;</p>, null, f, f, 6b8601cc-e4fc-4f07-a911-fdeb1a38319d, 8add5308-8db9-40fd-8891-a3e26ac74463, 0af8eca0-12aa-40e7-a5ac-e2f64f9f9883)."
                    ],
                    "context": {
                        "self": "<django.db.ba...x7fbce93b7690>",
                        "sql": "'INSERT INTO ..., %s, %s, %s)'",
                        "params": "(False, None, datetime.date....timezone.utc), datetime.date....timezone.utc), UUID('cdaa42a...cdaea780dcdf'), UUID('0af8eca...e2f64f9f9883'), ...)",
                        "ignored_wrapper_args": "(False, {'connection': <DatabaseWrap...ias='default'>, 'cursor': <django.db.ba...x7fbce93b7690>})"
                    }
                }
            }
        }
    ]
}